{% set name = "pyemd" %}
{% set version = "0.5.1" %}
{% set sha256sum = "fc81c2116f8573e559dfbb8d73e03d9f73c22d0770559f406516984302e07e70" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win32]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - toolchain  # [unix]
    - python
    - setuptools
    - numpy 1.9.*   # [not win]
    - numpy 1.10.*  # [win and py<36]
    - numpy 1.11.*  # [win and py>=36]

  run:
    - python
    - numpy >=1.9,<2.0.0

test:
  requires:
    - pytest

  source_files:
    - test/

  commands:
    - pytest -v test/

about:
  home: http://github.com/wmayner/pyemd
  license: MIT
  license_file: LICENSE
  summary: A Python wrapper for the Earth Mover's Distance.
  description: |
    PyEMD is a Python wrapper for Ofir Pele and Michael Werman’s implementation
    of the Earth Mover’s Distance that allows it to be used with NumPy.
  doc_url: http://github.com/wmayner/pyemd
  dev_url: http://github.com/wmayner/pyemd

extra:
  recipe-maintainers:
    - rmax
