{% set name = "pyemd" %}
{% set version = "0.4.4" %}
{% set sha256sum = "2457a0066fed668a6d9a0dd89ea6171110dd5d210f0c92c9662799908f37c08f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy         # [not win]
    - numpy         # [win and py<36]
    - numpy         # [win and py>=36]

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest

  source_files:
    - test/

  commands:
    - pytest -v test/

about:
  home: http://github.com/wmayner/pyemd
  license: MIT
  license_file: LICENSE
  summary: A Python wrapper for the Earth Mover's Distance.
  description: |
    PyEMD is a Python wrapper for Ofir Pele and Michael Werman’s implementation
    of the Earth Mover’s Distance that allows it to be used with NumPy.
  doc_url: http://github.com/wmayner/pyemd
  dev_url: http://github.com/wmayner/pyemd

extra:
  recipe-maintainers:
    - rmax
