{% set name = "pyemd" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b42b5ae7b2d15b1d4dee63810ea798a39217e8a76b7b49c0eb63a84e0fd900fe

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vvv
  skip: true  # [win32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - numpy
    - packaging
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - setuptools

test:
  requires:
    - pytest

  source_files:
    - test/

  commands:
    - pytest -v test/

about:
  home: http://github.com/wmayner/pyemd
  license: MIT
  license_file: LICENSE
  summary: A Python wrapper for the Earth Mover's Distance.
  description: |
    PyEMD is a Python wrapper for Ofir Pele and Michael Werman’s implementation
    of the Earth Mover’s Distance that allows it to be used with NumPy.
  doc_url: http://github.com/wmayner/pyemd
  dev_url: http://github.com/wmayner/pyemd

extra:
  recipe-maintainers:
    - rmax
